### ISSUE TITLE
Wrong direction for arpeggio arrow down

### ISSUE THREAD

**Issue by rettinghaus** [fkretlow/sebastian#4]
There is a problem with the SMuFL code point U+EAAE (wiggleArpeggiatoDownArrow): 
![arpeg-002](https://user-images.githubusercontent.com/7693447/117351318-df11e800-aead-11eb-91f0-4ea71cb44388.png)
It seems to be rotated by 180 degrees.

**Comment by benwiggy** [comment]
Hmm. It seems to be correct here. Are you sure you have the latest version and JSON file?

**Comment by benwiggy** [comment]
The position of the arrow isn't quite perfect, though. I'll adjust it and release a new version, which hopefully will improve things for you, soon.

**Comment by rettinghaus** [comment]
@benwiggy Thanks for the quick response. I opened the latest release in fontforge, and indeed, it disagrees with SMuFL specifications. It should point into the other direction. 
![image](https://user-images.githubusercontent.com/7693447/117409867-f71b5300-af11-11eb-9eac-b408e1bfcab3.png)

**Comment by benwiggy** [comment]
That's the same as in the SMUFL standard, and in Bravura. Up arrow points right, Down points left.

**Comment by rettinghaus** [comment]
My bad! Obviously the SMuFL specification changed on this one: 
https://www.smufl.org/version/latest/range/multiSegmentLines/
https://w3c.github.io/smufl/latest/tables/multi-segment-lines.html

Thanks for the nice font!
