### ISSUE TITLE
wiggleArpeggiatoUp repeatOffset

### ISSUE THREAD

**Issue by bezdonas** [fkretlow/sebastian#5]
https://github.com/fkretlow/sebastian/blob/master/fonts/Sebastian.json contains y repeatOffset for wiggleArpeggiatoUp symbol.

Whats the reason?

If it its drawn with that repeatOffset in mind, then arpeggiato looks like pisa tower :-)

![Screenshot 2023-11-06 at 19 01 12](https://github.com/fkretlow/sebastian/assets/3534038/e2c74865-001a-406a-8711-6f57df2bba37)

**Comment by benwiggy** [comment]
Which app are you using?

**Comment by bezdonas** [comment]
@benwiggy I am not using an app, I'm a developer, who tries to implement the font into an app :)

I can just not use said y offset since arpeggio doesn't have it(well, it goes up). However highlighting the problem in case it is not intended 😃

**Comment by benwiggy** [comment]
I'll have a look at it. Thanks.

**Comment by rettinghaus** [comment]
@bezdonas Obviously you are adding a horizontal offset too, which should not happen.

**Comment by benwiggy** [comment]
Yes, that's the repeat Offset -- the point where the glyph begins again.

**Comment by benwiggy** [comment]
The repeat Offset for arpeggios in the JSON file now has a value in only one axis.
