### ISSUE TITLE
Trill speed problem

### ISSUE THREAD

**Issue by Nikoteemus** [fkretlow/sebastian#6]
I have a problem with Sebastian when trying to use variable trill speed (slow -> fast) in Dorico. The result I get is from normal speed to abruptly fast speed. Is there a way to get it to work like it works in Bravura? See attached screenshots from both cases.
<img width="511" alt="bravura" src="https://github.com/fkretlow/sebastian/assets/47433777/502ee2b7-a07f-4338-871f-f06003411020">
<img width="513" alt="sebastian" src="https://github.com/fkretlow/sebastian/assets/47433777/7a587f0d-fc5f-41a8-94ca-64b2684701b7">

**Comment by benwiggy** [comment]
I'll have a look at it. In the mean time, you should be able to switch in the Bravura glyphs in Dorico's Music Symbols Editor.

**Comment by rettinghaus** [comment]
The simple reason for this is that the glyphs EAA0, EAA1, EAA2, and EAA3 are identical.

**Comment by benwiggy** [comment]
Actually, the problem is a missing bit of JSON. Dorico doesn't (I believe) distinguish between Fast, Faster and Fastest: it just uses Fast, Normal and Slow.

**Comment by benwiggy** [comment]
This revised JSON file should fix it for now. I'll issue a revised version of the font with some other tweaks and a new JSON file in a couple of weeks.
[Sebastian.json](https://github.com/fkretlow/sebastian/files/14550739/Sebastian.json)

You will need to restart Dorico; and you may have to re-apply Sebastian as the Music Font to update the file. (You can uncheck the options in the Music Font selection dialog.)

**Comment by Nikoteemus** [comment]
Excellent, thank you. I will test the fix.

**Comment by benwiggy** [comment]
Trill lines have been improved in v.1.12.
